### ISSUE TITLE
Build failing with SSG using pre-defined paths

### ISSUE THREAD

**Issue by luanfonceca** [BuilderIO/nextjs-builder-edge-personalization#2]
Hey, I'm integrating a couple of builder pages to use in our new site, I had expectations to use this project to base myself. Everything was working great but when I tried to set the `getStaticPaths` to static generate all of our pages the build started to fail.

Here are the changes I did into this repo:
```diff
diff --git a/pages/builder/[hash].tsx b/pages/builder/[hash].tsx
index 7f3d02a..598a832 100644
--- a/pages/builder/[hash].tsx
+++ b/pages/builder/[hash].tsx
@@ -42,10 +42,16 @@ export async function getStaticProps({ params } : GetStaticPropsContext<{ hash:
 }

 export async function getStaticPaths() {
+  const pages = await builder.getAll('page', {
+    // We only need the URL field
+    fields: 'data.url',
+    options: { noTargeting: true },
+  });
+
   return {
-    paths: [],
-    fallback: true
-  }
+    paths: pages.map(page => `/builder${page.data?.url}`),
+    fallback: true,
+  };
 }

 export default function Path({ page, attributes, locale }: InferGetStaticPropsType<typeof getStaticProps>) {
```

And the traceback I got after running the `npm run build` is:
```
Error occurred prerendering page "/builder/home". Read more: https://nextjs.org/docs/messages/prerender-error
SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.fromRewrite (/Users/luan/Sources/nextjs-builder-edge-personalization/node_modules/@builder.io/personalization-utils/dist/personalized-url.js:30:33)
    at getStaticProps (/Users/luan/Sources/nextjs-builder-edge-personalization/.next/server/pages/builder/[hash].js:70:82)
    at renderToHTML (/Users/luan/Sources/nextjs-builder-edge-personalization/node_modules/next/dist/server/render.js:451:26)
    at async /Users/luan/Sources/nextjs-builder-edge-personalization/node_modules/next/dist/export/worker.js:251:36
    at async Span.traceAsyncFn (/Users/luan/Sources/nextjs-builder-edge-personalization/node_modules/next/dist/trace/trace.js:79:20)
```

I got the same error for all my pages. I have a hint that the ```pages.map(page => `/builder${page.data?.url}`),``` isn't the right way to do this, but I couldn't find references on how to fix that. Unfortunately I'm not really an expert in Next.js to figure this out myself, so appreciate any help from you, and also if this is not the place to ask that I'm happy to leave a post in the forum.builder.io site.

**Comment by teleaziz** [comment]
Hey @luanfonceca, it's not designed to be used this way [`/builder/...urlPath`] , it's actually `/builder/[hash]` where hash is the result of the rewrite we do in the [`middleware`](https://github.com/BuilderIO/nextjs-builder-edge-personalization/blob/main/middleware.ts) where we take cookies and query params into account, pre-defining paths here is unnecessary but if you must for any reason, recommend generating the hash using the same approach in the middleware file then passing it to the `paths` array in `getStaticPaths`
